### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by sferry** [irods/irods_auth_plugin_kerberos#17]
Hi,
I 've installed the auth_plugin_kerberos packaged in rpm.
I've followed the documentation, and on the server modified /etc/krb5.conf
with :
[ realms]
 EXAMPLE.FR = {
  kdc = server.example.fr
  admin_server = server.example.fr
 }
[domain_realm]
 .example.fr = EXAMPLE.FR
 example.fr = EXAMPLE.FR

The kdc server is an AD I do not admin, but a simple user "irods"is defined.

On the client, I cannot authenticate I get : 
[user@client ] ils
[-]     /tmp/tmpix2hj6/krb/libkrb.cpp:1226:irods::error krb_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [Call to rcAuthResponseFailed.]

 failed with error -116104 SYS_SOCK_READ_ERR Connection reset by peer

What does it mean ? Is there some information missing in the doc regarding the necessary configuration, or something else ?

Thanks for any help.
Cheers
Sophie

**Comment by trel** [comment]
Did you get it to work?

What was the fix?

**Comment by sferry** [comment]
Hi
Yes I did.

-One (my) mistake was missing the capital letters in the cmd : iadmin aua user user@EXAMPLE.ORG<mailto:user@EXAMPLE.ORG>.

-One difficulty was to be sure the Active Directory actually had the right SPN (sometimes discussion with windows admin is not simple)
In this case the way to do it was with the commands:
[]$ net -n $(hostname -s) ads join -U someAuthADUser createcomputer="someADComputerGroup" createupn=host/$(hostname -s).example.org@EXAMPLE.ORG<mailto:.example.org@EXAMPLE.ORG>
Which added the host in the AD, and create a keytab (/etc/krb5.keytab)
And
[]$ net ads keytab add irods -U someAuthADUser
Which created the SPN for irods
And added the right lines in the keytab.
I separated the 2 output keytabs : the first for the host in /etc/krb5.keytab ; the 2nd for irods in /var/lib/irods/irods.keytab
(Maybe it is not necessary to split it, I didn’t check.)

- Add the env variable in /etc/irods/server_config.json
    "environment_variables": {
       "KRB5_KTNAME": "/var/lib/irods/irods.keytab"
    },
I think it works as well if the user irods (IrodsAdmin) has it defined in its env.

-Where to add the variables in the /etc/irods/server_config.json
 "KerberosServicePrincipal": "irods/server.example.org@EXAMPLE.ORG",   ## HERE !!
"KerberosKeytab": "/var/lib/irods/irods.keytab",                                                     ## HERE !!
 "plugin_configuration": {
        "authentication": {
                 "KerberosServicePrincipal": "irods/server.example.org@EXAMPLE.ORG",   ## NOT THERE !!
                 "KerberosKeytab": "/var/lib/irods/irods.keytab"                                                       ##  NOT THERE !!
   },

And that’s about it ….
Cheers
Sophie

De : Terrell Russell [mailto:notifications@github.com]
Envoyé : mardi 17 octobre 2017 16:08
À : irods/irods_auth_plugin_kerberos <irods_auth_plugin_kerberos@noreply.github.com>
Cc : FERRY Sophie <sophie.ferry@cea.fr>; State change <state_change@noreply.github.com>
Objet : Re: [irods/irods_auth_plugin_kerberos] Cannot make it work (#17)


Did you get it to work?

What was the fix?
