### ISSUE TITLE
Build failed: krbAuthRequest.hpp missing

### ISSUE THREAD

**Issue by jmarshall** [irods/irods_auth_plugin_kerberos#5]
g++ -DRODS_SERVER  [...] libkrb.cpp
    libkrb.cpp:15:10: fatal error: 'krbAuthRequest.hpp' file not found

Where is this file supposed to be found?  3605720b8d8f56630201f3731dc853b9824fceb9's commit message and #4's title suggest that perhaps `git add krbAuthRequest.hpp` was forgotten before that was committed...

**Comment by trel** [comment]
It's now in there - 01a2566d0 - please try again and close when satisfied.

**Comment by jmarshall** [comment]
It builds now, thanks.
